spring:
  h2:
    console:
      path: /my-h2-console
  datasource:
    url: jdbc:h2:file:./db/links
    username: smykolaj
    password: test
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
